src/deploy/scope_resourcegroup.ts

Correction

---

.gitignore
.vscode/launch.json
tsconfig.json

Steps for debugging:
1. npm install
2. npm install -g @zeit/ncc
3. ncc build src/entrypoint.ts -s -o _build
4. az login
5. On VS Code, press F5

enable local debugging

---

.github/CODEOWNERS
.github/workflows/ci-workflow.yml
HowToDebug.md
src/deploy/scope_managementgroup.ts
src/deploy/scope_resourcegroup.ts
src/deploy/scope_subscription.ts
test/main.tests.ts
test/parameters.json
test/template.json

- Added all scopes in ci-workflow
- It covers providing template/parameters as url/repo file path
- Added code owners file
- Added howToDebug.md file

Fixing ci tests and adding code owners

---

README.md
action.yml
examples/exampleGuide.md

Fixing : https://github.com/github/azure-integration/issues/5

Updates in action.yaml

---

package-lock.json
package.json

This is as per the security vulnerability : https://github.com/Azure/arm-deploy/network/alert/package-lock.json/@actions%2Fcore/open

Upgrade @actions/core to version 1.2.6 or later

---

HowToDebug.md
ReleaseProcess.md

Documenting steps that are to be followed while releasing a new version of the action.

Documentation for ReleaseProcess

---

README.md

Updated Readme for Azure ARM Deploy Action

Updated Readme for Azure ARM Deploy Action

---

README.md

Refer to GitHub issue https://github.com/Azure/arm-deploy/issues/32

update README. Add yaml example to ensure az RG created

---

.github/workflows/ci-workflow.yml

The templates were recently moved from the original location.
PR - https://github.com/Azure/azure-quickstart-templates/pull/9453

Updated template URL in CI-Workflow

---

README.md

Based on this issue https://github.com/Azure/arm-deploy/issues/37

Corrected location in Example

---

dist/index.js
src/deploy/scope_managementgroup.ts
src/deploy/scope_resourcegroup.ts
src/deploy/scope_subscription.ts

Temporary fix for this https://github.com/Azure/arm-deploy/issues/48

Fixed whitespaced StdErr issue

---

.github/config/labels.yml
.github/workflows/add-labels.yml

Adding this workflow to all action repos. This will help us create labels as described in this [doc](https://docs.google.com/document/d/1kW04WxeNtpx9VQD3v3UJdij5-frJ5D91ZSA26Hs34OA/edit#)

Added add-label-workflow

---

.github/CODEOWNERS
.github/config/labels.yml
.github/workflows/add-labels.yml
README.md

Synced releases/v1 with main as part of this WI https://github.com/github/azure-integration/issues/342

Brought releases/v1 in sync with main

---

.github/ISSUE_TEMPLATE/bug-report---feature-request.md
.github/workflows/ci-workflow.yml
.github/workflows/defaultLabel.yml
README.md
action.yml
package-lock.json
package.json
src/deploy/scope_managementgroup.ts
src/deploy/scope_resourcegroup.ts
src/deploy/scope_subscription.ts
src/main.ts
test/main.tests.ts
test/resourceGroup-Negative/parameters.json
test/resourceGroup-Negative/template.json
test/subscription-Negative/template.json

Cherry-picked these PRs
https://github.com/Azure/arm-deploy/pull/64
https://github.com/Azure/arm-deploy/pull/63
https://github.com/Azure/arm-deploy/pull/61

Cherry picked commits from main

---

.github/workflows/ci-workflow.yml

Add Scheduler and also add slack Notification

Add Scheduler and also add slack Notification

---

.github/workflows/ci-workflow.yml

Had to delete the MG, commenting out this test as a temporary workaround.
```
Hello deepak,
You are receiving this notification because you have been identified as the owner of an unsanctioned Management Group (MG) tree (structure). 
Please delete the whole "tree". You can find instructions on how to cleanup your MG node(s) at https://aka.ms/MGCleanup.  
If you have subscriptions in the "tree", please move them to the Governed Management Group tree of your division (let us know if you need the point of contacts).
!IMPORTANT!
If you have a valid reason to keep it, please get back to us before 6/9/21 for an exception, in order to not be remediated by our service.
Provide:GroupId, RootGroupId(if the MG is not on the root), Exception Reason, Organization you are part of.
Your MG(s) with ID …
```

Commented out MG test

---

README.md

Update README.md az group creation script

---

test/main.tests.ts

Fix arm deploy issue

---

README.md

Clarify that you can override parameters locally in conjunction with using parameter files.
Closes #83

docs: Clarify that you can override parameters locally

---

.github/workflows/ci-workflow.yml
README.md
package-lock.json
test/main.tests.ts

Cherry picked all the test-related commits made to correct flaky tests. 
[issue](https://github.com/github/c2c-actions/issues/4396)

Synced master and releases/v1

---

README.md

As part of on going work with Kanchan's team to improve actions, we are adding this section on Gayatri's recommendation.

Added Az CLI dependency section

---

.github/policies/issueMgmt.recentActivity.yml

Autoreply thanked for contributing to bicep, removed the ref to bicep.

Updated autoreply on stale issues

---

README.md

change examples to use v2 instead of v1 (which has warnings about deprecated features)

Documentation - Update examples on readme
